# Generated by Django 3.0.2 on 2020-01-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctanswer',
            name='user_drawn_images',
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='user_drawn_images',
            field=models.ManyToManyField(blank=True, related_name='doodle1', to='doodle.Image'),
        ),
    ]
