# Generated by Django 3.0.2 on 2020-01-14 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0002_auto_20200114_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='correct_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doodle1', to='doodle.CorrectAnswer'),
        ),
    ]
