# Generated by Django 3.0.2 on 2020-01-14 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0003_auto_20200114_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='image',
            name='correctAnswer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doodle', to='doodle.CorrectAnswer'),
        ),
    ]
