# Generated by Django 3.0.2 on 2020-01-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0004_auto_20200114_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='correctAnswer',
            new_name='correct_answer',
        ),
    ]
