# Generated by Django 3.0.2 on 2020-01-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0006_auto_20200114_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctanswer',
            old_name='correct_answer',
            new_name='answer',
        ),
    ]
