# Generated by Django 3.0.2 on 2020-01-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0007_auto_20200115_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctanswer',
            old_name='answer',
            new_name='correct_answer',
        ),
    ]
