# Generated by Django 3.0.2 on 2020-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0008_auto_20200115_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user_drawn_image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
