# Generated by Django 3.0.1 on 2019-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfBear', models.CharField(max_length=50)),
                ('designatedName', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
