# Generated by Django 3.0.1 on 2020-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0002_auto_20191218_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
